/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    GEMINI_API_KEY: process.env.GEMINI_API_KEY,
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    ADMIN_EMAIL: process.env.ADMIN_EMAIL,
    RESEND_FROM_NAME: process.env.RESEND_FROM_NAME,
    RESEND_FROM_EMAIL: process.env.RESEND_FROM_EMAIL,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    CRON_SECRET: process.env.CRON_SECRET,
  },
  allowedDevOrigins: ["*.preview.same-app.com"],
  images: {
    domains: [
      "source.unsplash.com",
      "images.unsplash.com",
      "ext.same-assets.com",
      "ugc.same-assets.com",
      "wpbfwgwxxcplaclkdbzi.supabase.co",
    ],
    remotePatterns: [
      {
        protocol: "https",
        hostname: "source.unsplash.com",
        pathname: "/**",
      },
      {
        protocol: "https",
        hostname: "images.unsplash.com",
        pathname: "/**",
      },
      {
        protocol: "https",
        hostname: "ext.same-assets.com",
        pathname: "/**",
      },
      {
        protocol: "https",
        hostname: "ugc.same-assets.com",
        pathname: "/**",
      },
      {
        protocol: "https",
        hostname: "wpbfwgwxxcplaclkdbzi.supabase.co",
        pathname: "/storage/v1/object/public/**",
      },
    ],
  },
  async redirects() {
    return [
      // ─── Global WWW to Non-WWW Redirect ─────────────────────────────────────
      {
        source: '/:path*',
        has: [
          {
            type: 'host',
            value: 'www.led-sign.ca',
          },
        ],
        destination: 'https://led-sign.ca/:path*',
        permanent: true,
      },
      { source: "/why-programmable-led-signs/", destination: "/blog/why-programmable-led-signs", permanent: true },
      { source: "/why-programmable-led-signs", destination: "/blog/why-programmable-led-signs", permanent: true },
      { source: "/so-many-options-when-it-comes-down-to-brochures/", destination: "/blog/so-many-options-when-it-comes-down-to-brochures", permanent: true },
      { source: "/so-many-options-when-it-comes-down-to-brochures", destination: "/blog/so-many-options-when-it-comes-down-to-brochures", permanent: true },
      { source: "/vinyl-printing-simplest-option-for-large-format-advertising/", destination: "/blog/vinyl-printing", permanent: true },
      { source: "/vinyl-printing-simplest-option-for-large-format-advertising", destination: "/blog/vinyl-printing", permanent: true },
      { source: "/make-any-phrase-into-a-neon-sign-with-one-click/", destination: "/blog/make-any-phrase-into-a-neon-sign", permanent: true },
      { source: "/make-any-phrase-into-a-neon-sign-with-one-click", destination: "/blog/make-any-phrase-into-a-neon-sign", permanent: true },
      { source: "/why-business-cards/", destination: "/blog/why-business-cards", permanent: true },
      { source: "/why-business-cards", destination: "/blog/why-business-cards", permanent: true },
      { source: "/why-roll-up-banners/", destination: "/blog/why-roll-up-banners", permanent: true },
      { source: "/why-roll-up-banners", destination: "/blog/why-roll-up-banners", permanent: true },
      { source: "/billboards/", destination: "/blog/billboards", permanent: true },
      { source: "/billboards", destination: "/blog/billboards", permanent: true },
      { source: "/retractable-banners/", destination: "/blog/retractable-banners", permanent: true },
      { source: "/retractable-banners", destination: "/blog/retractable-banners", permanent: true },
      { source: "/programmable-led-sign/", destination: "/led-display-signs", permanent: true },
      { source: "/programmable-led-sign", destination: "/led-display-signs", permanent: true },
      { source: "/billboards-and-their-impact-on-business/", destination: "/blog/billboards", permanent: true },
      { source: "/billboards-and-their-impact-on-business", destination: "/blog/billboards", permanent: true },
      { source: "/neon-sign/", destination: "/neon-signs", permanent: true },
      { source: "/neon-sign", destination: "/neon-signs", permanent: true },
      { source: "/metal-sign/", destination: "/custom-signs", permanent: true },
      { source: "/metal-sign", destination: "/custom-signs", permanent: true },
      { source: "/mesh/", destination: "/custom-banners", permanent: true },
      { source: "/mesh", destination: "/custom-banners", permanent: true },
      { source: "/led-channel-letter/", destination: "/custom-signs/channel-letter-signs", permanent: true },
      { source: "/led-channel-letter", destination: "/custom-signs/channel-letter-signs", permanent: true },
      { source: "/front-store-signs/", destination: "/custom-signs", permanent: true },
      { source: "/front-store-signs", destination: "/custom-signs", permanent: true },
      { source: "/all-about-led-signs-toronto-4168388994/", destination: "/blog/all-about-led-signs", permanent: true },
      { source: "/all-about-led-signs-toronto-4168388994", destination: "/blog/all-about-led-signs", permanent: true },
      { source: "/led-panels-toronto/", destination: "/led-display-signs", permanent: true },
      { source: "/led-panels-toronto", destination: "/led-display-signs", permanent: true },
      { source: "/install-led-channel/", destination: "/custom-signs/channel-letter-signs", permanent: true },
      { source: "/install-led-channel", destination: "/custom-signs/channel-letter-signs", permanent: true },
      { source: "/full-color-led-display-screen-citylight-sign/", destination: "/led-display-signs", permanent: true },
      { source: "/full-color-led-display-screen-citylight-sign", destination: "/led-display-signs", permanent: true },
      { source: "/product-category/led-signs/", destination: "/led-display-signs", permanent: true },
      { source: "/product-category/led-signs", destination: "/led-display-signs", permanent: true },
      { source: "/product-category/printing/", destination: "/marketing-materials", permanent: true },
      { source: "/product-category/printing", destination: "/marketing-materials", permanent: true },
      { source: "/product-category/custom-signs/", destination: "/custom-signs", permanent: true },
      { source: "/product-category/custom-signs", destination: "/custom-signs", permanent: true },
      { source: "/contact-rgb-sign-screen-sign-for-store-citylight-group/", destination: "/contact-us", permanent: true },
      { source: "/contact-rgb-sign-screen-sign-for-store-citylight-group", destination: "/contact-us", permanent: true },
      { source: "/refund_returns/", destination: "/return-policy", permanent: true },
      { source: "/refund_returns", destination: "/return-policy", permanent: true },
      { source: "/request-quote/", destination: "/get-a-quote", permanent: true },
      { source: "/request-quote", destination: "/get-a-quote", permanent: true },
      { source: "/quote-rental-industrial-led-displays-rgb-sign-print/", destination: "/get-a-quote", permanent: true },
      { source: "/quote-rental-industrial-led-displays-rgb-sign-print", destination: "/get-a-quote", permanent: true },
      { source: "/about-us-citylight-group-citylight-sign/", destination: "/about-us", permanent: true },
      { source: "/about-us-citylight-group-citylight-sign", destination: "/about-us", permanent: true },
      { source: "/category/posts/", destination: "/blog", permanent: true },
      { source: "/category/posts", destination: "/blog", permanent: true },
      { source: "/products-led-sign-board/", destination: "/led-display-signs", permanent: true },
      { source: "/products-led-sign-board", destination: "/led-display-signs", permanent: true },
      { source: "/product/full-color-custom-led-sign-board/", destination: "/led-display-signs", permanent: true },
      { source: "/product/full-color-custom-led-sign-board", destination: "/led-display-signs", permanent: true },
      { source: "/product/full-color-electronic-signs/", destination: "/led-display-signs", permanent: true },
      { source: "/product/full-color-electronic-signs", destination: "/led-display-signs", permanent: true },
      { source: "/product/full-color-programmable-led-display/", destination: "/led-display-signs", permanent: true },
      { source: "/product/full-color-programmable-led-display", destination: "/led-display-signs", permanent: true },
      { source: "/product/full-color-digital-display-screen/", destination: "/led-display-signs", permanent: true },
      { source: "/product/full-color-digital-display-screen", destination: "/led-display-signs", permanent: true },
      { source: "/product/full-color-led-scrolling-sign/", destination: "/led-display-signs", permanent: true },
      { source: "/product/full-color-led-scrolling-sign", destination: "/led-display-signs", permanent: true },
      { source: "/product/full-color-led-display-screen/", destination: "/led-display-signs/gallery", permanent: true },
      { source: "/product/full-color-led-display-screen", destination: "/led-display-signs/gallery", permanent: true },
      { source: "/product/programmable-led-signs/", destination: "/led-display-signs/gallery", permanent: true },
      { source: "/product/programmable-led-signs", destination: "/led-display-signs/gallery", permanent: true },
      { source: "/product/car-magnet-signs-led-signs-toronto/", destination: "/vehicle-signs", permanent: true },
      { source: "/product/car-magnet-signs-led-signs-toronto", destination: "/vehicle-signs", permanent: true },
      { source: "/product/full-color-outdoor-led-sign/", destination: "/led-display-signs", permanent: true },
      { source: "/product/full-color-outdoor-led-sign", destination: "/led-display-signs", permanent: true },
      { source: "/product/indoor-full-color-led-display-indoor4168388994/", destination: "/led-display-signs", permanent: true },
      { source: "/product/indoor-full-color-led-display-indoor4168388994", destination: "/led-display-signs", permanent: true },
      { source: "/product/flyer/", destination: "/marketing-materials", permanent: true },
      { source: "/product/flyer", destination: "/marketing-materials", permanent: true },
      { source: "/product/light-box-sign-led-backlight-sign-illuminated/", destination: "/custom-signs", permanent: true },
      { source: "/product/light-box-sign-led-backlight-sign-illuminated", destination: "/custom-signs", permanent: true },
      { source: "/product/brochure-printing-design-4168388994/", destination: "/marketing-materials", permanent: true },
      { source: "/product/brochure-printing-design-4168388994", destination: "/marketing-materials", permanent: true },
      { source: "/product/banners-vinyl-fabric-mesh-rull-up-retractable/", destination: "/custom-banners", permanent: true },
      { source: "/product/banners-vinyl-fabric-mesh-rull-up-retractable", destination: "/custom-banners", permanent: true },
      { source: "/product/neon-led-signs-neon-sign-led-sign/", destination: "/neon-signs", permanent: true },
      { source: "/product/neon-led-signs-neon-sign-led-sign", destination: "/neon-signs", permanent: true },
      { source: "/product/led-poster-smart-led-poster-1-416-8388994/", destination: "/led-display-signs", permanent: true },
      { source: "/product/led-poster-smart-led-poster-1-416-8388994", destination: "/led-display-signs", permanent: true },
      { source: "/product/pylon-signs-and-all-about-pylon-signs-buy/", destination: "/custom-signs", permanent: true },
      { source: "/product/pylon-signs-and-all-about-pylon-signs-buy", destination: "/custom-signs", permanent: true },
      { source: "/product/front-store-signs-and-all-about-front-store/", destination: "/custom-signs", permanent: true },
      { source: "/product/front-store-signs-and-all-about-front-store", destination: "/custom-signs", permanent: true },
      { source: "/product/business-card-custom-design-toronto-4168388994/", destination: "/marketing-materials", permanent: true },
      { source: "/product/business-card-custom-design-toronto-4168388994", destination: "/marketing-materials", permanent: true },
      { source: "/product/bag-lawn-signs-yard-signs-by-rgb-sign-print/", destination: "/custom-signs/yard-signs", permanent: true },
      { source: "/product/bag-lawn-signs-yard-signs-by-rgb-sign-print", destination: "/custom-signs/yard-signs", permanent: true },
      { source: "/product/custom-t-shirt/", destination: "/marketing-materials", permanent: true },
      { source: "/product/custom-t-shirt", destination: "/marketing-materials", permanent: true },
      { source: "/product/single-color-programable-led-sign-led-screen/", destination: "/led-display-signs", permanent: true },
      { source: "/product/single-color-programable-led-sign-led-screen", destination: "/led-display-signs", permanent: true },
      { source: "/product/car-wrap/", destination: "/custom-signs", permanent: true },
      { source: "/product/car-wrap", destination: "/custom-signs", permanent: true },
      { source: "/product/real-estate-signs-all-about-real-estate-signs/", destination: "/custom-signs/real-estate-panels", permanent: true },
      { source: "/product/real-estate-signs-all-about-real-estate-signs", destination: "/custom-signs/real-estate-panels", permanent: true },
      { source: "/product/light-box-sign-custom-signage-services/", destination: "/custom-signs", permanent: true },
      { source: "/product/light-box-sign-custom-signage-services", destination: "/custom-signs", permanent: true },
      { source: "/product/led-channel-letters/", destination: "/custom-signs/channel-letter-signs", permanent: true },
      { source: "/product/led-channel-letters", destination: "/custom-signs/channel-letter-signs", permanent: true },

      // ─── Missing WordPress page slugs ───────────────────────────────────────
      { source: "/FkShow2022.zip", destination: "/", permanent: true },
      { source: "/product/vinyl-banners-fabric-banners-mesh-banners-rull-up-retractable-banners", destination: "/custom-banners", permanent: true },
      { source: "/product/full-color-led-display-led_display_screen-led_channel_letters-led_light_boxes-sign-print", destination: "/led-display-signs", permanent: true },
      { source: "/product/priting-lightbox-lighting-led-backlight-signage-lightbox-framed-illuminated-signs", destination: "/custom-signs", permanent: true },
      { source: "/product/printing-flyer-designing", destination: "/marketing-materials", permanent: true },
      { source: "/product/personalised-mug", destination: "/marketing-materials", permanent: true },
      { source: "/product/priting-light-box", destination: "/custom-signs", permanent: true },
      { source: "/product/channel-letter-signs", destination: "/custom-signs/channel-letter-signs", permanent: true },
      { source: "/User%20Manual%20Of%20FK%20Show%20LED%20Picture%20&%20Text%20Edit%20Software.doc", destination: "/", permanent: true },
      { source: "/product/led-display-full-color-indoor", destination: "/led-display-signs", permanent: true },
      { source: "/product/led-display-single-color", destination: "/led-display-signs", permanent: true },
      { source: "/product/full-color-led-display", destination: "/led-display-signs", permanent: true },
      { source: "/product/printing-flyer", destination: "/marketing-materials", permanent: true },
      { source: "/product/led-display-single-color-digital-signage-digital-display-board-outdoor-led-display", destination: "/led-display-signs", permanent: true },
      { source: "/product/single-color-led-display", destination: "/led-display-signs", permanent: true },
      { source: "/product/brochureshow-to-make-a-brochure-4168388994", destination: "/marketing-materials", permanent: true },
      { source: "/product/printing-brochures", destination: "/marketing-materials", permanent: true },
      { source: "/product/printing-banner", destination: "/custom-banners", permanent: true },
      { source: "/personalized-decals", destination: "/custom-decals", permanent: true },
      { source: "/product/led-poster-display", destination: "/led-display-signs", permanent: true },
      { source: "/product/printing-business-card", destination: "/marketing-materials", permanent: true },
      { source: "/projects/", destination: "/projects", permanent: true },
      { source: "/elementor-7114/", destination: "/", permanent: true },
      { source: "/elementor-7114", destination: "/", permanent: true },
      { source: "/cart-advertising-signs-electronic-led-reader/", destination: "/", permanent: true },
      { source: "/cart-advertising-signs-electronic-led-reader", destination: "/", permanent: true },
      { source: "/led-sign/", destination: "/led-display-signs/gallery", permanent: true },
      { source: "/led-sign", destination: "/led-display-signs/gallery", permanent: true },
      { source: "/led-display-sign/", destination: "/led-display-signs/gallery", permanent: true },
      { source: "/led-display-sign", destination: "/led-display-signs/gallery", permanent: true },
      { source: "/led-display-screens/", destination: "/led-display-signs/gallery", permanent: true },
      { source: "/led-display-screens", destination: "/led-display-signs/gallery", permanent: true },
      { source: "/programmable-led-signs/", destination: "/led-display-signs", permanent: true },
      { source: "/programmable-led-signs", destination: "/led-display-signs", permanent: true },
      { source: "/channel-letter-signs/", destination: "/custom-signs/channel-letter-signs", permanent: true },
      { source: "/channel-letter-signs", destination: "/custom-signs/channel-letter-signs", permanent: true },
      { source: "/neon-signs/", destination: "/neon-signs", permanent: true },
      { source: "/custom-signs/", destination: "/custom-signs", permanent: true },
      { source: "/custom-banners/", destination: "/custom-banners", permanent: true },
      { source: "/custom-flags/", destination: "/custom-flags", permanent: true },
      { source: "/led-display-signs/", destination: "/led-display-signs/gallery", permanent: true },
      { source: "/get-a-quote/", destination: "/get-a-quote", permanent: true },
      { source: "/contact-us/", destination: "/contact-us", permanent: true },
      { source: "/about-us/", destination: "/about-us", permanent: true },
      { source: "/blog/", destination: "/blog", permanent: true },
      { source: "/return-policy/", destination: "/return-policy", permanent: true },

      // ─── Old WooCommerce / WordPress specific paths ──────────────────────────
      { source: "/shop/", destination: "/", permanent: true },
      { source: "/shop", destination: "/", permanent: true },
      { source: "/cart/", destination: "/", permanent: true },
      { source: "/cart", destination: "/", permanent: true },
      { source: "/checkout/", destination: "/checkout", permanent: true },
      { source: "/my-account/", destination: "/login", permanent: true },
      { source: "/my-account", destination: "/login", permanent: true },
      { source: "/wp-sitemap.xml", destination: "/sitemap.xml", permanent: true },
      { source: "/sitemap_index.xml", destination: "/sitemap.xml", permanent: true },
      { source: "/page-sitemap.xml", destination: "/sitemap.xml", permanent: true },
      { source: "/post-sitemap.xml", destination: "/sitemap.xml", permanent: true },

      // ─── Old quote page variants ──────────────────────────────────────────────
      { source: "/quote-rental-industrial-led-displays/", destination: "/get-a-quote", permanent: true },
      { source: "/quote-rental-industrial-led-displays", destination: "/get-a-quote", permanent: true },
      {
        source: "/signs",
        destination: "/custom-signs",
        permanent: true,
      },
      {
        source: "/banners",
        destination: "/custom-banners",
        permanent: true,
      },
      {
        source: "/flags",
        destination: "/custom-flags",
        permanent: true,
      },
      {
        source: "/tradeshow",
        destination: "/trade-show",
        permanent: true,
      },
      {
        source: "/stickers-decals",
        destination: "/custom-decals",
        permanent: true,
      },
      {
        source: "/sign-holders",
        destination: "/sign-accessories",
        permanent: true,
      },
      {
        source: "/signs/:path*",
        destination: "/custom-signs/:path*",
        permanent: true,
      },
      {
        source: "/banners/:path*",
        destination: "/custom-banners/:path*",
        permanent: true,
      },
    ];
  },
};

module.exports = nextConfig;
